In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV, train_test_split, cross_validate
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('./data/wunderground_scraped_data.csv')
df.head(3)

,Temp_max,Temp_avg,Temp_min,Dew_max,Dew_avg,Dew_min,Hum_max,Hum_avg,Hum_min,Wind_max,Wind_avg,Wind_min,Pres_max,Pres_avg,Pres_min,Precipitation,Date
0,21,15.3,6,17,8.8,-6,93,76.0,58,22,12.2,0,29.8,29.7,29.6,0.0,1999-1-1
1,26,22.4,18,25,20.8,16,100,93.5,86,31,19.9,7,29.6,29.1,28.8,0.0,1999-1-2
2,25,14.0,5,24,9.4,0,96,81.8,71,21,17.4,14,29.3,29.0,28.7,0.0,1999-1-3

In [3]:
df.Date = pd.to_datetime(df.Date, format="%Y-%M-%d")

In [4]:
y = df.Temp_avg.shift(-3,axis=0)

In [5]:
y.iloc[7669] = df.Temp_avg.iloc[2]
y.iloc[7670] = df.Temp_avg.iloc[1]
y.iloc[7671] = df.Temp_avg.iloc[0]

In [6]:
X_num = df.select_dtypes(include='number')
X_num = X_num.drop('Temp_avg',axis=1)
X = (X_num - X_num.mean()) / X_num.std()
X.head(3)

,Temp_max,Temp_min,Dew_max,Dew_avg,Dew_min,Hum_max,Hum_avg,Hum_min,Wind_max,Wind_avg,Wind_min,Pres_max,Pres_avg,Pres_min,Precipitation
0,-1.790709,-1.907250,-1.552186,-1.625805,-1.639072,0.591588,0.532052,0.499409,0.914458,0.720427,-0.855672,2.070572,1.555088,0.299399,-0.188746
1,-1.553707,-1.278230,-1.113554,-0.989699,-0.653243,1.281010,1.912986,2.320044,2.522830,2.870251,1.244749,1.043353,-0.726904,-0.186968,-0.188746
2,-1.601107,-1.959669,-1.168383,-1.594000,-1.370209,0.887054,0.989733,1.344704,0.735750,2.172256,3.345169,-0.497476,-1.107236,-0.247764,-0.188746

In [7]:
lr = LinearRegression()
lr.fit(X, y)
R2_train = lr.score(X,y)

In [8]:
test = pd.read_csv('./data/Recent_data.csv')
test.head(3)

,Temp_max,Temp_avg,Temp_min,Dew_max,Dew_avg,Dew_min,Hum_max,Hum_avg,Hum_min,Wind_max,Wind_avg,Wind_min,Pres_max,Pres_avg,Pres_min,Precipitation,Date
0,91,83.08,77,72,68.79,64,79,60,48,16,7,5,29.47,29.43,29.39,0,5-11-2022
1,92,81.04,71,69,65.13,60,73,50,44,15,10,7,29.40,29.35,29.30,0,5-10-2022

In [9]:
test = test.drop(['Temp_avg','Date'], axis=1)

In [10]:
test = (test - X_num.mean()) / X_num.std()
X_test = test.iloc[0,:]
test

,Temp_max,Temp_min,Dew_max,Dew_avg,Dew_min,Hum_max,Hum_avg,Hum_min,Wind_max,Wind_avg,Wind_min,Pres_max,Pres_avg,Pres_min,Precipitation
0,1.527313,1.814452,1.463410,1.554194,1.497655,-0.787256,-0.730517,-0.150818,-0.157790,-0.731403,0.644629,0.375661,0.528192,0.171728,-0.188746
1,1.574713,1.499942,1.298923,1.360182,1.318414,-1.378189,-1.519622,-0.410909,-0.336498,0.106191,1.244749,0.016134,0.223926,0.117011,-0.188746

In [11]:
lr.predict([X_test])

array([82.55729102])

In [12]:
R2_train

0.7788753650657221